# Generated by Django 5.1.2 on 2026-01-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profilepost"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePostMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.ImageField(upload_to="profile_posts/")),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "post",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="profiles.profilepost",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="profilepostmedia",
            index=models.Index(fields=["post", "position"], name="profiles_pr_post_id_7f4d1e_idx"),
        ),
    ]

