# Generated by Django 5.1.2 on 2026-01-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_votes_comments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profilepost',
            new_name='profiles_pr_author__da51f5_idx',
            old_name='profiles_pr_author__a4b2fb_idx',
        ),
        migrations.RenameIndex(
            model_name='profilepostcomment',
            new_name='profiles_pr_post_id_985ad1_idx',
            old_name='profiles_pr_post_id_36bca9_idx',
        ),
        migrations.RenameIndex(
            model_name='profilepostmedia',
            new_name='profiles_pr_post_id_092f0f_idx',
            old_name='profiles_pr_post_id_7f4d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='profilepostvote',
            new_name='profiles_pr_post_id_bddb98_idx',
            old_name='profiles_pr_post_id_8b5f65_idx',
        ),
    ]
